spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 458394365094-5dq5h3q32mjaf3vuo4p5kqev8pf4sv3l.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8888/user-manager/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo